### PR TITLE
Fix git "dubious ownership" error

### PR DESCRIPTION
**Pull request by j8r**
I've no idea why this new error showed up. From my research it doesn't come from f-e-d-c itself.

### CODE REVIEW

**Comment by Lctrs** [comment]
Where did it showed up ?

**Comment by j8r** [comment]
We can see this errors in the GitHub Actions runs history, you may have received notifications about this failed builds too.

**Comment by Lctrs** [comment]
https://github.com/flathub/net.rpcs3.RPCS3/actions/runs/4325866941/jobs/7552569107 thank you @j8r !

**Comment by Lctrs** [comment]
@j8r still doesn't work

**Comment by j8r** [comment]
😕

**Comment by j8r** [comment]
Works on the CI but not when triggered by the timer, that's strange 😕

**Comment by Lctrs** [comment]
I triggered it manually one hour ago and it failed.

**Pull request merged**
