### PR TITLE
Run merge workflow 1 hour after update

### PR DESCRIPTION
**Pull request by j8r**
Follow up of #1240 .
Indeed the merge workflow ran 15 minutes after the update one, which is too short.

### CODE REVIEW

**Comment by Lctrs** [comment]
@j8r I tried to run it manually and it did nothing.

**Comment by j8r** [comment]
Then we should probably ask @barthalion if he has any idea how to do it, if any.
How can we only merge opened PRs by the bot, without creating new ones?

**Comment by j8r** [comment]
Another take:
- use two cron expression to trigger two subsequent execution instead of one single expression, it could work this way
- `sed` on the second run to prevent f-e-d-c to fetch newer commits. It will then see the already opened PR and merge it, hopefully.

**Comment by Lctrs** [comment]
I would prefer using https://github.com/mikefarah/yq instead of sed.

**Comment by j8r** [comment]
It is fine here, I don't know if yq is available in the ubuntu Action.
If it is, better to use it indeed. Otherwise, downloading it seems superfluous.

**Pull request merged**
