### PR TITLE
Update to LLVM 16

### PR DESCRIPTION
**Pull request by j8r**

### CODE REVIEW

**Comment by j8r** [comment]
Extension not available yet :confused:

**Comment by Lctrs** [comment]
@j8r llvm 16 is now available on flathub. If I understand the last commits on the subject, they do not seem to rely on their fork but use directly the upstream llvm 16. Am I correct ?

**Comment by j8r** [comment]
That's true, in https://github.com/RPCS3/rpcs3/tree/master/3rdparty/llvm, `llvm` is pointing to https://github.com/llvm/llvm-project.

We could avoid to build LLVM then, but the risk however is to have a broken build when they'll require, say LLVM 17, but it's not yet available on flathub.

**Comment by Lctrs** [comment]
If ittapi is not used anymore, we can remove its source.

**Pull request merged**
